### ISSUE TITLE
Repeated spam blocking on the same comment

### ISSUE THREAD

**Issue by sussyamongussussy** [dthung1602/the-spamminator#1]
Ignore my name. So, there was this spam reply on a normal comment, so I restored the comment, and then restored the spam reply, and the spam blocking started repeating itself on the normal comment. 
![image](https://user-images.githubusercontent.com/105838329/174147261-957bb93d-e1db-4f8d-964a-367083d1a417.png)

**Comment by dthung1602** [comment]
@sussyamongussussy  Thanks for your feedback. I'll try to fix it

**Comment by dthung1602** [comment]
Fix in version 1.2.1
Released for Chrome: 2022-06-22
Released for Firefox: 2022-06-21
